config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'users#index'
  get  '/profile',    to: 'users#profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, World!"
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json

  def profile

  end

  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :kebab, :bio, :slack)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "WHY NOT KEBAB", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "PROFILE",   profile_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KebabIsTheBest</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name, class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email, class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :kebab %>
    <%= form.check_box :kebab, id: :user_kebab, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_field :bio, id: :user_bio, class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :slack %>
    <%= form.text_field :slack, id: :user_slack, class: 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>TOUS LES CORSAIRS</h1>

<table>
  <!-- <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Kebab</th>
      <th>Bio</th>
      <th>Slack</th>
      <th colspan="3"></th>
    </tr>
  </thead> -->

  <div class = "row">
    <% @users.each do |user| %>
          <div class = "col-md-5 center corsair">
            <div class = "col-md-4">
              <%= user.name %>
            </div>
            <div class = "col-md-4">
              <%= user.email %>
            </div>
            <div class = "col-md-4">
              <% if user.kebab == true %>
                KEBAB
              <% else %>
                HUMMUS
              <% end %>
            </div>
            <!-- <td><%= user.bio %></td>
            <td><%= user.slack %></td> -->
            <!-- <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          </div>
    <% end %>
  </div>
    <br>
    <div class = "row">
      <div class ="col-md-12 center">
        <button type="button" href = "<% new_user_path %>" class="btn btn-primary">CREATE NEW PROFILE</button>
        <button type="button" href = "<%= new_user_path %>" class="btn btn-primary">CHANGE YOUR CHOICE</button>
      </div>
    </div>


<!-- <%= link_to 'New User', new_user_path %> -->

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/profile.html.erb
<a>Salut</a>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p clas>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Kebab:</strong>
  <%= @user.kebab %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>Slack:</strong>
  <%= @user.slack %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>